# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-10 16:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cart_State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connect', models.IntegerField(default=1, editable=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Cart')),
                ('food', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restaurant.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('billed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order_State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('uncooked', 'uncooked'), ('cooked', 'cooked'), ('cancelled', 'cancelled')], default='uncooked', max_length=10)),
                ('food', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restaurant.Food')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_food',
            field=models.ManyToManyField(through='order.Order_State', to='restaurant.Food'),
        ),
        migrations.AddField(
            model_name='order',
            name='table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='carted_food',
            field=models.ManyToManyField(through='order.Cart_State', to='restaurant.Food'),
        ),
        migrations.AddField(
            model_name='cart',
            name='table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
