# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-28 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order_state',
            table='food_state',
        ),
    ]
