# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-17 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_food',
            field=models.ManyToManyField(blank=True, null=True, through='order.Order_State', to='restaurant.Food'),
        ),
        migrations.AlterField(
            model_name='order_state',
            name='state',
            field=models.CharField(choices=[('ordered', 'ordered'), ('making', 'making'), ('finished', 'finished'), ('served', 'served'), ('cancelled', 'cancelled')], default='ordered', max_length=10),
        ),
    ]
