# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-17 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200417_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_food',
            field=models.ManyToManyField(blank=True, default=None, null=True, through='order.Order_State', to='restaurant.Food'),
        ),
    ]
