# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-28 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200329_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='order_state',
            name='food',
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_food',
            field=models.ManyToManyField(related_name='food_states', through='order.Order_State', to='order.Person'),
        ),
        migrations.AddField(
            model_name='order_state',
            name='person',
            field=models.ForeignKey(default='hi', on_delete=django.db.models.deletion.CASCADE, to='order.Person'),
        ),
    ]
