# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-28 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        ('order', '0005_auto_20200329_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.RemoveField(
            model_name='order_state',
            name='number',
        ),
        migrations.RemoveField(
            model_name='order_state',
            name='person',
        ),
        migrations.AddField(
            model_name='order_state',
            name='food',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restaurant.Food'),
        ),
        migrations.AddField(
            model_name='order_state',
            name='state',
            field=models.CharField(choices=[(1, 'uncooked'), (2, 'cooked'), (3, 'cancelled')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_food',
            field=models.ManyToManyField(through='order.Order_State', to='restaurant.Food'),
        ),
        migrations.AlterModelTable(
            name='order_state',
            table=None,
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
