# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-31 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20200329_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_state',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order_state',
            name='state',
            field=models.CharField(choices=[('uncooked', 'uncooked'), ('cooked', 'cooked'), ('cancelled', 'cancelled')], default='uncooked', max_length=10),
        ),
    ]
