# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-06 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200406_2214'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
